row_1 = '+ {:-<8} + {:-^12} + {:->9} +'.format('','','')
row_2 = '+ {:<8} + {:^12} + {:>9} +'.format('ID','Ho va ten','Noi sinh')
row_3 = '+ {:<8} + {:^12} + {:>9} +'.format('1','Miku Ohashi','Japanse')
row_4 = '+ {:<8} + {:^12} + {:>9} +'.format('2','Lena Ander','America')
row_5 = '+ {:-<8} + {:-^12} + {:->9} +'.format('','','')
print(row_1)
print(row_2)
print(row_3)
print(row_4)
print(row_5)
a = 'nguyen hoan'
b = a.center(30)
c = '{:^30}'.format(a)
print(b)
print(c)